# Generated by Django 6.0.6 on 2026-06-21 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.product'),
        ),
    ]
