# Generated by Django 6.0.6 on 2026-06-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_user_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPurchaseCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Products',
        ),
        migrations.AddField(
            model_name='user',
            name='first_purchase_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.firstpurchasecoupon'),
        ),
        migrations.AddField(
            model_name='user',
            name='Products',
            field=models.ManyToManyField(null=True, to='pages.product'),
        ),
    ]
