# Generated by Django 6.0.6 on 2026-06-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_firstpurchasecoupon_remove_user_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Products',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, to='pages.product'),
        ),
    ]
