# Generated by Django 6.0.6 on 2026-06-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('descrption', models.TextField()),
            ],
        ),
    ]
