# Generated by Django 6.0.6 on 2026-06-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='_is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='descrption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%y/%m/%d'),
        ),
    ]
