# Generated by Django 6.0.6 on 2026-06-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_category_product__category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_price',
            new_name='price',
        ),
    ]
