# Generated by Django 6.0.6 on 2026-06-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producta',
        ),
        migrations.AlterModelOptions(
            name='producta',
            options={'ordering': ['created_at'], 'verbose_name': 'phone'},
        ),
    ]
